# Generated by Django 5.1.1 on 2024-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='form',
            name='tags',
        ),
        migrations.AddField(
            model_name='form',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app.category'),
        ),
        migrations.AddField(
            model_name='form',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
    ]
