# Generated by Django 5.1.1 on 2024-11-21 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_formverificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="assigned_admins",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "admin"},
                related_name="assigned_admin_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
