# Generated by Django 5.1.1 on 2024-11-14 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='assigned_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
