# Generated by Django 5.1.1 on 2024-11-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_form_assigned_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
