# Generated by Django 5.1.1 on 2024-11-14 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_form_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allowed_managers',
            field=models.ManyToManyField(blank=True, related_name='allowed_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
