# Generated by Django 5.1.1 on 2024-11-16 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_form_allowed_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sub_role",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    (
                        "user-access-to-all-users-with-role-user",
                        "User Access to All Users with Role User",
                    ),
                    (
                        "manager-access-to-all-users-with-role-manager",
                        "Manager Access to All Users with Role Manager",
                    ),
                ],
                default="none",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="added_managers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "manager"},
                related_name="viewable_manager_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="added_users",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "user"},
                related_name="viewable_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
