# Generated by Django 5.1.1 on 2024-11-16 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_customuser_sub_role_form_added_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="added_managers",
        ),
        migrations.RemoveField(
            model_name="form",
            name="assigned_manager",
        ),
        migrations.AddField(
            model_name="form",
            name="assigned_managers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "manager"},
                related_name="assigned_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sub_role",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    (
                        "user-access-to-all-users-with-role-user",
                        "User Access to All Users with Role User",
                    ),
                    (
                        "manager-access-to-all-users-with-role-manager",
                        "user Access to All Users with Role Manager",
                    ),
                ],
                default="none",
                max_length=255,
            ),
        ),
    ]
