# Generated by Django 5.1.1 on 2024-11-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_form_added_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="categories",
        ),
        migrations.AddField(
            model_name="form",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="form",
            name="tags",
            field=models.ManyToManyField(to="app.tag"),
        ),
    ]
