# Generated by Django 5.1.1 on 2024-11-16 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_form_categories_form_category_alter_form_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="form",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="app.category",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="forms", to="app.tag"
            ),
        ),
    ]
