# Generated by Django 5.1.1 on 2024-11-19 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_categories", "0002_remove_usercategory_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercategorymembership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="usercategorymembership",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_per_category"
            ),
        ),
    ]
